Revert "crossbuild: Update DJGPP binutils bnu226sr3 => bnu2261s"
This reverts commit 5a8573ffbd5bbbef13014572899127a9d6b4e2a0.

bnu2261s fails to build:
../../bnu2261s/bfd/coffswap.h: In function ‘coff_swap_scnhdr_in’:
../../bnu2261s/bfd/coffswap.h:775:7: error: ‘coff_64k_relocation_enabled’ undeclared (first use in this function)